function getMonths() {
  const months = new Date().getMonth();
  return months + 1 < 10 ? '0' + (months + 1) : months + 1;
}
function getYear() {
  const year = new Date().getFullYear();
  return year;
}
export const query = (date: string, limit: number) => `
SELECT 
mb.MASTER_BILL_ID, mb.BASIC, mb.TAX, mb.DISCOUNT, mb.OUTSTANDING, mb.BILL_AMOUNT, mb.CREATE_TIME, 
acc.ACCOUNT_NO, acc.OLD_ACCOUNT, acc.FORW_FAMI_NAME, acc.FORW_GIVE_NAME, acc.FORW_ADDRESS, 
cusi.CUSTOMER_NO, cust.CUST_TYPE_DESC, cust.CUST_TYPE_EN, 
mti.ROUTE_ID, mti.WALK_ORDER,
-- tard.START_SEG, tard.END_SEG, tard.STEP_RATE, tard.STEP_CONSUMPTION, tard.MONEY, tard.METER_ID,
-- cd.BRANCH_CODE, 
-- br.BRANCH_NAME, br.BRANCH_NAME_EN, 
-- mr.READER_ID, mr.READING_DATE,
tl.MULTIPLIER, tl.CONSUMPTION, tl.LAST_READING, tl.CURRENT_READING, tl.METER_RENT,tl.L_READING_TIME, tl.C_READING_TIME,
-- r.ROUTE_ID, r.DISTRICT,
d.TELEPHONE_NO, d.DISTRICT_CODE, d.REGION_CODE, 
rc.REGION_DESC, rc.REGION_DESC_ENG,
ass.STATUS
FROM MASTER_BILL mb
INNER JOIN ACCOUNT acc ON mb.ACCOUNT_NO = acc.ACCOUNT_NO
INNER JOIN CUSTOMER_INFO cusi ON acc.ACCOUNT_NO = cusi.CUSTOMER_ID
INNER JOIN CUSTOMER_TYPE cust ON cusi.CUSTOMER_TYPE = cust.CUSTOMER_TYPE
INNER JOIN METER_INSTALL mti ON mti.ACCOUNT_NO = acc.ACCOUNT_NO
-- INNER JOIN TARIFF_DETAIL tard ON mb.MASTER_BILL_ID = tard.BILL_ID
-- INNER JOIN CREDIT cd ON cd.METER_ID1 = mti.METER_ID
-- INNER JOIN BRANCH br ON br.BRANCH_CODE = cd.BRANCH_CODE
-- INNER JOIN METER_READ mr ON mr.METER_ID = mti.METER_ID
INNER JOIN TARIFF_LIST tl ON tl.MASTER_BILL_ID = mb.MASTER_BILL_ID
INNER JOIN ROUTE r ON r.ROUTE_ID = mti.ROUTE_ID
INNER JOIN DISTRICT d ON d.DISTRICT_CODE = r.DISTRICT
INNER JOIN REGION_CODE rc ON rc.REGION_CODE = d.REGION_CODE
INNER JOIN ASSISMASTER ass ON ass.MASTER_BILL_ID = mb.MASTER_BILL_ID
-- INNER JOIN PAYMENT pm ON acc.ACCOUNT_NO = (SELECT p.ACCOUNT_NO FROM PAYMENT p WHERE p.ACCOUNT_NO = acc.ACCOUNT_NO ORDER BY p.PAYMENT_ID DESC OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY)
-- WHERE mb.ACCOUNT_NO = 178604
AND mti.METER_STATUS = 'M01'
-- AND TO_CHAR(mb.CREATE_TIME, 'yyyymm') = '${
  getYear().toString() + getMonths().toString()
}'
AND TO_CHAR(mb.CREATE_TIME, 'yyyymm') = ${date}
AND ROWNUM <= ${limit}
-- AND tard.MINI_CHARGE = 'M'
`;
export const queryCustomer = (date: string, limit: number) => `
SELECT 
mb.MASTER_BILL_ID, mb.BASIC, mb.TAX, mb.DISCOUNT, mb.OUTSTANDING, mb.BILL_AMOUNT, mb.CREATE_TIME, 
acc.ACCOUNT_NO, acc.OLD_ACCOUNT, acc.FORW_FAMI_NAME, acc.FORW_GIVE_NAME, acc.FORW_ADDRESS, 
cusi.CUSTOMER_NO, cust.CUST_TYPE_DESC, cust.CUST_TYPE_EN, 
mti.ROUTE_ID, mti.WALK_ORDER,
tard.START_SEG, tard.END_SEG, tard.STEP_RATE,tard.APPLIED_TARIFF, tard.STEP_CONSUMPTION, tard.MONEY, tard.METER_ID, tard.MINI_CHARGE,
tl.MULTIPLIER, tl.CONSUMPTION, tl.LAST_READING, tl.CURRENT_READING, tl.METER_RENT,tl.L_READING_TIME, tl.C_READING_TIME,tl.CURRENCY,
ass.STATUS
FROM MASTER_BILL mb
INNER JOIN ACCOUNT acc ON mb.ACCOUNT_NO = acc.ACCOUNT_NO
INNER JOIN CUSTOMER_INFO cusi ON acc.ACCOUNT_NO = cusi.CUSTOMER_ID
INNER JOIN CUSTOMER_TYPE cust ON cusi.CUSTOMER_TYPE = cust.CUSTOMER_TYPE
INNER JOIN METER_INSTALL mti ON mti.ACCOUNT_NO = acc.ACCOUNT_NO
INNER JOIN TARIFF_DETAIL tard ON mb.MASTER_BILL_ID = tard.BILL_ID
INNER JOIN TARIFF_LIST tl ON tl.MASTER_BILL_ID = mb.MASTER_BILL_ID
INNER JOIN ROUTE r ON r.ROUTE_ID = mti.ROUTE_ID
INNER JOIN ASSISMASTER ass ON ass.MASTER_BILL_ID = mb.MASTER_BILL_ID
WHERE mti.METER_STATUS = 'M01'
AND TO_CHAR(mb.CREATE_TIME, 'yyyymm') = ${date}
AND ROWNUM <= ${limit}
`;
